-- Insert tags
INSERT INTO tags (key) VALUES
('asian'),
('chinese'),
('japanese'),
('south-korean'),
('vietnamese'),
('thai'),
('westerner'),
('french'),
('italian'),
('spanish'),
('irish'),
('russian'),
('south-american'),
('mexican'),
('appetizer'),
('main-dish'),
('dessert'),
('entremet'),
('meat'),
('fish'),
('vegan'),
('vegetarian');

INSERT INTO tag_languages (tag_id, lang, name) VALUES
((SELECT id FROM tags WHERE key='asian'), 'en', 'Asian'),
((SELECT id FROM tags WHERE key='asian'), 'fr', 'Asiatique'),
((SELECT id FROM tags WHERE key='chinese'), 'en', 'Chinese'),
((SELECT id FROM tags WHERE key='chinese'), 'fr', 'Chinoise'),
((SELECT id FROM tags WHERE key='japanese'), 'en', 'Japanese'),
((SELECT id FROM tags WHERE key='japanese'), 'fr', 'Japonaise'),
((SELECT id FROM tags WHERE key='south-korean'), 'en', 'South Korean'),
((SELECT id FROM tags WHERE key='south-korean'), 'fr', 'Sud Coréenne'),
((SELECT id FROM tags WHERE key='vietnamese'), 'en', 'Vietnamese'),
((SELECT id FROM tags WHERE key='vietnamese'), 'fr', 'Vietnamienne'),
((SELECT id FROM tags WHERE key='thai'), 'en', 'Thai'),
((SELECT id FROM tags WHERE key='thai'), 'fr', 'Thaïlandaise'),
((SELECT id FROM tags WHERE key='westerner'), 'en', 'Westerner'),
((SELECT id FROM tags WHERE key='westerner'), 'fr', 'Occidentale'),
((SELECT id FROM tags WHERE key='french'), 'en', 'French'),
((SELECT id FROM tags WHERE key='french'), 'fr', 'Francaise'),
((SELECT id FROM tags WHERE key='italian'), 'en', 'Italian'),
((SELECT id FROM tags WHERE key='italian'), 'fr', 'Italienne'),
((SELECT id FROM tags WHERE key='spanish'), 'en', 'Spanish'),
((SELECT id FROM tags WHERE key='spanish'), 'fr', 'Espagnole'),
((SELECT id FROM tags WHERE key='irish'), 'en', 'Irish'),
((SELECT id FROM tags WHERE key='irish'), 'fr', 'Irelandaise'),
((SELECT id FROM tags WHERE key='russian'), 'en', 'Russian'),
((SELECT id FROM tags WHERE key='russian'), 'fr', 'Russe'),
((SELECT id FROM tags WHERE key='south-american'), 'en', 'South American'),
((SELECT id FROM tags WHERE key='south-american'), 'fr', 'Sud Américaine'),
((SELECT id FROM tags WHERE key='mexican'), 'en', 'Mexican'),
((SELECT id FROM tags WHERE key='mexican'), 'fr', 'Mexicaine'),
((SELECT id FROM tags WHERE key='appetizer'), 'en', 'Appetizer'),
((SELECT id FROM tags WHERE key='appetizer'), 'fr', 'Entrée'),
((SELECT id FROM tags WHERE key='main-dish'), 'en', 'Main Dish'),
((SELECT id FROM tags WHERE key='main-dish'), 'fr', 'Plat Principal'),
((SELECT id FROM tags WHERE key='dessert'), 'en', 'Dessert'),
((SELECT id FROM tags WHERE key='dessert'), 'fr', 'Dessert'),
((SELECT id FROM tags WHERE key='entremet'), 'en', 'Entremet'),
((SELECT id FROM tags WHERE key='entremet'), 'fr', 'Entremet'),
((SELECT id FROM tags WHERE key='meat'), 'en', 'Meat'),
((SELECT id FROM tags WHERE key='meat'), 'fr', 'Viande'),
((SELECT id FROM tags WHERE key='fish'), 'en', 'Fish'),
((SELECT id FROM tags WHERE key='fish'), 'fr', 'Poisson'),
((SELECT id FROM tags WHERE key='vegan'), 'en', 'Vegan'),
((SELECT id FROM tags WHERE key='vegan'), 'fr', 'Vegan'),
((SELECT id FROM tags WHERE key='vegetarian'), 'en', 'Vegetarian'),
((SELECT id FROM tags WHERE key='vegetarian'), 'fr', 'Végétarienne');
